/*
 * Una scelta per oggetto, dove JB2A gratuito ha un effetto dedicato o molto vicino. Vince
 * sulle regole (regole.mjs). Le chiavi sono quelle di chiavi.mjs: `dnd5e.<tipo>.<identifier>`.
 *
 * Gli incantesimi sono controllati contro l'elenco dell'SRD 2024 di dnd5e 6.0.3; i privilegi
 * usano l'identifier atteso nel PHB 2024, da confermare dentro Foundry
 * (docs/verifiche-in-foundry.md). Resta una proposta: conta come appare, e lo dice Prova.
 */

export const ASSEGNAZIONI_DND = Object.freeze({
  // incantesimi — proiettili
  "dnd5e.spell.fire-bolt":         { file: "jb2a.fire_bolt.orange", forma: "proiettile" },
  "dnd5e.spell.produce-flame":     { file: "jb2a.fire_bolt.orange", forma: "proiettile" },
  "dnd5e.spell.magic-missile":     { file: "jb2a.magic_missile.purple", forma: "proiettile" },
  "dnd5e.spell.guiding-bolt":      { file: "jb2a.guiding_bolt.01.blueyellow", forma: "proiettile" },
  "dnd5e.spell.eldritch-blast":    { file: "jb2a.eldritch_blast.purple", forma: "proiettile" },
  "dnd5e.spell.ray-of-frost":      { file: "jb2a.ray_of_frost.blue", forma: "proiettile" },
  "dnd5e.spell.chain-lightning":   { file: "jb2a.chain_lightning.primary.blue", forma: "proiettile" },
  "dnd5e.spell.scorching-ray":     { file: "jb2a.scorching_ray.01.orange", forma: "proiettile" },
  "dnd5e.spell.witch-bolt":        { file: "jb2a.witch_bolt.blue", forma: "proiettile" },
  "dnd5e.spell.disintegrate":      { file: "jb2a.disintegrate.green", forma: "proiettile" },
  "dnd5e.spell.finger-of-death":   { file: "jb2a.energy_strands.range.standard.purple.01", forma: "proiettile" },
  "dnd5e.spell.sunbeam":           { file: "jb2a.guiding_bolt.01.blueyellow", forma: "proiettile" },
  // incantesimi — coni e linee, tesi dal lanciatore
  "dnd5e.spell.burning-hands":     { file: "jb2a.burning_hands.01.orange", forma: "proiettile" },
  "dnd5e.spell.cone-of-cold":      { file: "jb2a.cone_of_cold.blue", forma: "proiettile" },
  "dnd5e.spell.lightning-bolt":    { file: "jb2a.lightning_bolt.wide.blue", forma: "proiettile" },
  "dnd5e.spell.gust-of-wind":      { file: "jb2a.gust_of_wind.default", forma: "proiettile" },
  "dnd5e.spell.poison-spray":      { file: "jb2a.breath_weapons.poison.cone.green", forma: "proiettile" },
  // incantesimi — aree
  "dnd5e.spell.fireball":          { file: "jb2a.fireball.explosion.orange", forma: "area" },
  "dnd5e.spell.delayed-blast-fireball": { file: "jb2a.fireball.explosion.orange", forma: "area" },
  "dnd5e.spell.meteor-swarm":      { file: "jb2a.fireball.explosion.orange", forma: "area" },
  "dnd5e.spell.flame-strike":      { file: "jb2a.flames.04.complete.orange", forma: "area" },
  "dnd5e.spell.fire-storm":        { file: "jb2a.flames.04.complete.orange", forma: "area" },
  "dnd5e.spell.shatter":           { file: "jb2a.shatter.blue", forma: "area" },
  "dnd5e.spell.thunderwave":       { file: "jb2a.thunderwave.center.blue", forma: "area" },
  "dnd5e.spell.sleep":             { file: "jb2a.sleep.cloud.01.pink", forma: "area" },
  "dnd5e.spell.call-lightning":    { file: "jb2a.call_lightning.high_res.blue", forma: "area" },
  "dnd5e.spell.moonbeam":          { file: "jb2a.moonbeam.01.complete.blue", forma: "area" },
  "dnd5e.spell.black-tentacles":   { file: "jb2a.black_tentacles.dark_purple", forma: "area" },
  "dnd5e.spell.darkness":          { file: "jb2a.darkness.black", forma: "area" },
  "dnd5e.spell.web":               { file: "jb2a.web.01", forma: "area" },
  "dnd5e.spell.wall-of-fire":      { file: "jb2a.wall_of_fire.300x100.yellow", forma: "area" },
  "dnd5e.spell.wall-of-force":     { file: "jb2a.wall_of_force.sphere.grey", forma: "area" },
  "dnd5e.spell.entangle":          { file: "jb2a.entangle.green", forma: "area" },
  "dnd5e.spell.fog-cloud":         { file: "jb2a.fog_cloud.01.white", forma: "area" },
  "dnd5e.spell.grease":            { file: "jb2a.grease.dark_brown.loop", forma: "area" },
  "dnd5e.spell.sleet-storm":       { file: "jb2a.sleet_storm.blue", forma: "area" },
  "dnd5e.spell.ice-storm":         { file: "jb2a.ice_spikes.radial.burst.white", forma: "area" },
  "dnd5e.spell.plant-growth":      { file: "jb2a.plant_growth.03.round.4x4.complete.greenyellow", forma: "area" },
  "dnd5e.spell.faerie-fire":       { file: "jb2a.dancing_light.purplegreen", forma: "area" },
  "dnd5e.spell.stinking-cloud":    { file: "jb2a.fumes.04.loop.grey", forma: "area" },
  "dnd5e.spell.cloudkill":         { file: "jb2a.fumes.04.loop.grey", forma: "area" },
  "dnd5e.spell.circle-of-death":   { file: "jb2a.arms_of_hadar.dark_purple", forma: "area" },
  // incantesimi — sul bersaglio
  "dnd5e.spell.sacred-flame":      { file: "jb2a.sacred_flame.target.yellow", forma: "bersaglio" },
  "dnd5e.spell.toll-the-dead":     { file: "jb2a.toll_the_dead.green.complete", forma: "bersaglio" },
  "dnd5e.spell.spiritual-weapon":  { file: "jb2a.spiritual_weapon.mace.spectral.blue", forma: "bersaglio" },
  "dnd5e.spell.flaming-sphere":    { file: "jb2a.flaming_sphere.200px.orange.01", forma: "bersaglio" },
  "dnd5e.spell.hunters-mark":      { file: "jb2a.hunters_mark.pulse.01.green", forma: "bersaglio" },
  "dnd5e.spell.divine-smite":      { file: "jb2a.divine_smite.target.blueyellow", forma: "bersaglio" },
  "dnd5e.spell.arcane-hand":       { file: "jb2a.arcane_hand.blue", forma: "bersaglio" },
  "dnd5e.spell.ice-knife":         { file: "jb2a.ice_spikes.radial.burst.white", forma: "bersaglio" },
  "dnd5e.spell.chill-touch":       { file: "jb2a.energy_strands.in.green.01", forma: "bersaglio" },
  "dnd5e.spell.inflict-wounds":    { file: "jb2a.toll_the_dead.green.skull_smoke", forma: "bersaglio" },
  "dnd5e.spell.harm":              { file: "jb2a.toll_the_dead.green.skull_smoke", forma: "bersaglio" },
  "dnd5e.spell.blight":            { file: "jb2a.energy_strands.in.green.01", forma: "bersaglio" },
  "dnd5e.spell.vicious-mockery":   { file: "jb2a.markers.fear.dark_purple.01", forma: "bersaglio" },
  "dnd5e.spell.dissonant-whispers": { file: "jb2a.markers.fear.dark_purple.01", forma: "bersaglio" },
  "dnd5e.spell.acid-splash":       { file: "jb2a.liquid.splash.blue", forma: "bersaglio" },
  "dnd5e.spell.shocking-grasp":    { file: "jb2a.lightning_strike.blue", forma: "bersaglio" },
  "dnd5e.spell.sorcerous-burst":   { file: "jb2a.explosion.02.blue", forma: "bersaglio" },
  "dnd5e.spell.hellish-rebuke":    { file: "jb2a.flames.01.orange", forma: "bersaglio" },
  "dnd5e.spell.hex":               { file: "jb2a.condition.curse.01.001.red", forma: "bersaglio" },
  "dnd5e.spell.dispel-magic":      { file: "jb2a.magic_signs.rune.abjuration.complete.blue", forma: "bersaglio" },
  "dnd5e.spell.revivify":          { file: "jb2a.healing_generic.03.burst.bluegreen", forma: "bersaglio" },
  // incantesimi — cure e aiuti, dove li porta il bersaglio (auto)
  "dnd5e.spell.cure-wounds":       { file: "jb2a.cure_wounds.400px.blue", forma: "auto" },
  "dnd5e.spell.mass-cure-wounds":  { file: "jb2a.cure_wounds.400px.blue", forma: "auto" },
  "dnd5e.spell.healing-word":      { file: "jb2a.healing_generic.400px.blue", forma: "auto" },
  "dnd5e.spell.mass-healing-word": { file: "jb2a.healing_generic.400px.blue", forma: "auto" },
  "dnd5e.spell.heal":              { file: "jb2a.healing_generic.03.burst.bluegreen", forma: "auto" },
  "dnd5e.spell.bless":             { file: "jb2a.bless.400px.intro.yellow", forma: "auto" },
  "dnd5e.spell.bane":              { file: "jb2a.condition.curse.01.001.red", forma: "auto" },
  "dnd5e.spell.shield-of-faith":   { file: "jb2a.shield.01.complete.01.blue", forma: "auto" },
  "dnd5e.spell.mage-armor":        { file: "jb2a.shield.01.complete.01.blue", forma: "auto" },
  "dnd5e.spell.haste":             { file: "jb2a.on_token_buff.001.001.blue", forma: "auto" },
  // incantesimi — su chi lancia
  "dnd5e.spell.shield":            { file: "jb2a.shield.01.complete.01.blue", forma: "lanciatore" },
  "dnd5e.spell.misty-step":        { file: "jb2a.misty_step.01.blue", forma: "lanciatore" },
  "dnd5e.spell.dimension-door":    { file: "jb2a.misty_step.02.blue", forma: "lanciatore" },
  "dnd5e.spell.teleport":          { file: "jb2a.misty_step.02.blue", forma: "lanciatore" },
  "dnd5e.spell.spirit-guardians":  { file: "jb2a.spirit_guardians.blueyellow.ring", forma: "lanciatore" },
  "dnd5e.spell.arms-of-hadar":     { file: "jb2a.arms_of_hadar.dark_purple", forma: "lanciatore" },
  "dnd5e.spell.antilife-shell":    { file: "jb2a.antilife_shell.blue_no_circle", forma: "lanciatore" },
  "dnd5e.spell.dancing-lights":    { file: "jb2a.dancing_light.blueyellow", forma: "lanciatore" },
  "dnd5e.spell.detect-magic":      { file: "jb2a.detect_magic.circle.blue", forma: "lanciatore" },
  "dnd5e.spell.counterspell":      { file: "jb2a.magic_signs.rune.abjuration.complete.blue", forma: "lanciatore" },

  // privilegi di classe (identifier del PHB 2024, da confermare in Foundry)
  "dnd5e.feat.sneak-attack":        { file: "jb2a.sneak_attack.dark_green", forma: "bersaglio" },
  "dnd5e.feat.flurry-of-blows":     { file: "jb2a.flurry_of_blows.physical.blue", forma: "bersaglio" },
  "dnd5e.feat.bardic-inspiration":  { file: "jb2a.bardic_inspiration.greenorange", forma: "auto" },
  "dnd5e.feat.second-wind":         { file: "jb2a.healing_generic.200px.green", forma: "lanciatore" },
  "dnd5e.feat.lay-on-hands":        { file: "jb2a.healing_generic.200px.yellow", forma: "auto" },
  "dnd5e.feat.rage":                { file: "jb2a.on_token_buff.001.001.purplered", forma: "lanciatore" },
  "dnd5e.feat.action-surge":        { file: "jb2a.on_token_buff.001.001.blue", forma: "lanciatore" },
  "dnd5e.feat.cunning-action":      { file: "jb2a.smoke.puff.centered.grey", forma: "lanciatore" },
  "dnd5e.feat.channel-divinity":    { file: "jb2a.bless.400px.intro.yellow", forma: "lanciatore" },
  "dnd5e.feat.divine-smite":        { file: "jb2a.divine_smite.target.blueyellow", forma: "bersaglio" }
});
